@echo off
echo Checking configured git version...
git --version
echo Checking configured git lfs version...
git lfs version
if %errorlevel% neq 0 (
    echo Git LFS not found. Aborting LFS setup.
    exit /b 1
)
echo Initializing git repository...
git init
echo Installing git lfs...
git lfs install
echo Tracking large files...
git lfs track "*.h5"
echo Adding gitattributes...
git add .gitattributes
echo Removing .h5 from .gitignore (if present)...
type .gitignore | findstr /v "*.h5" > .gitignore.tmp
move /y .gitignore.tmp .gitignore
echo Staging files...
git add .
echo Committing files...
git commit -m "Initial commit with LFS for model"
echo Branching to main...
git branch -M main
echo Git setup complete.
